Implement Service Layer with Custom Exceptions in Ride Service
aremm23/microservices-taxi-api pull request #8
Opened 2024-11-08 10:50 UTC by aremm23

Developed the service layer for the ride service, ensuring business logic is encapsulated and properly structured. Added custom exceptions to improve error handling and code clarity. Created various DTOs and data files to facilitate seamless internal data transfer and interaction within the service. This enhancement sets the foundation for more robust and maintainable service operations.

2024-11-10 16:36 UTC, aleshkey requested changes

2024-11-10 16:36 UTC, aleshkey commented on ride-service/src/main/java/com/artsem/api/rideservice/service/impl/RideLifecycleServiceImpl.java
> +        rideRepository.save(ride);
обращаешься к бд, нет transactional

2024-11-10 16:36 UTC, aleshkey commented on ride-service/src/main/java/com/artsem/api/rideservice/service/impl/RideLifecycleServiceImpl.java
> +        } else if (userRole.equals(UserRole.PASSENGER)) {
для else лучше делать свой блок

2024-11-10 16:36 UTC, aleshkey commented on ride-service/src/main/java/com/artsem/api/rideservice/service/impl/RideLifecycleServiceImpl.java
> +        return rideRepository.findById(rideId).orElseThrow(RideNotFoundException::new);
оформи, как ты делал со стримами (.orElseThrow с новой строки)

2024-11-10 16:36 UTC, aleshkey commented on ride-service/src/main/java/com/artsem/api/rideservice/service/impl/RideDistanceServiceImpl.java
> +        if (response == null || !OK_STATUS.equals(response.getStatus()) || response.getRows().isEmpty() ||
большой if, лучше разбить на несколько строк

2024-11-11 12:42 UTC, aremm23 commented on ride-service/src/main/java/com/artsem/api/rideservice/service/impl/RideLifecycleServiceImpl.java
> +        rideRepository.save(ride);
А точно для одного документа в монго нужна @transactional?

2024-11-12 14:35 UTC, aleshkey approved these changes

2024-11-12 14:44 UTC, merged